---
- hosts: room_assistants
  pre_tasks:
    # ensures that network is stable
    - name: Stop room-assistant service
      become: yes
      systemd:
        name: room-assistant
        state: stopped
      ignore_errors: True
  roles:
    - role: nodejs
      tags: nodejs
    - role: room-assistant
      tags: room_assistant
